server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/technical_profile
    username: root
    application:
      name: profile
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect